name: Feature Request
description: If you want to request a change, improvement or feature in the engine
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
